title: al-hijrah group of school
description: 'privet school '
template:
  repo: al-hijrah-group-of-school-template
  name: al-hijrah-group-of-school
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
